version: "3.9"

services:
  mysql_db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=application
      - MYSQL_DATABASE=quest_web
    networks:
      - quest_web

  quest_web_java:
    build: ../Etape_4/.
    ports:
    - "8090:8090"
    networks:
      - quest_web
    depends_on:
    - mysql_db
    restart: always

networks:
  quest_web:
    driver: bridge