version: "3.9"

services:
  mysql_db:
    image: mysql:8
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-db:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_USER=application
      - MYSQL_DATABASE=quest_web